### ISSUE TITLE
v.0.9.9.0 SpringBoard Crash on iOS 8.3/8.4

### ISSUE THREAD

**Issue by jamesamndj** [phoenix3200/libstatusbar#18]
The new update for iOS 9 crashes the springboard for iOS 8.3 and 8.4 devices. Temporary downgrade available at http://elijahandandrew.com/repo.

**Comment by phoenix3200** [comment]
Crap.  Enums weren't strictly increasing for iOS versioning.  A new version is being posted ASAP.

**Comment by jamesamndj** [comment]
Thanks for your work.
